# Generated by Django 2.2.16 on 2022-10-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221027_2225'),
        ('users', '0002_auto_20221027_1522'),
    ]

    operations = [
    ]
